# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
### favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Gamma Cray
title: Jake Of All Trades
email: onepathleft@protonmail.com
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
### website: onepathleft.com/resume
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: "gammacray"
github_username:  "gammacray"
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Reddit
  icon: fab fa-reddit-alien
  url: reddit.com/u/onepathleft
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs

  Hello! In 2019 I made the jump from sailboat building to a digital skillset and a healthier lifestyle. In 2023 I'm upskilling again, moving towards more *proactive* work with more opportunity to flex some analytical and dev chops. I'm incredibly fond of working with people from around the world, from all walks of life. I thrive on discovering the goals of others and finding ways to get them there. Digital work is a lot like building sailboats - pulling lines out of thin air and making them real with any tool available, many of them improvised or built specifically for the task. 
  
  #### I bring practical experience and knowledge in;
  * GraphQL and REST API
  * Some SQL and Python, node.js, React (stoked to grow in these ELI5)
  * HTML, CSS, Liquid, YAML, Markdown, TLDR
  * Mode, Splunk, Datadog, Zendesk, Slack, Okta, TIL
  * Netlify, Git (Lab and Hub), Digital Ocean, AWS, NTA
  * Have worked fully remote since 2019
  * Linux, Winblows 3.1, MacOS, ChromeOS, Android

  #### I bring well-traveled wisdom and values from;
  * Freelance writing and static web design
  * Sailboat custom build and repair
  * Tiny-home construction
  * Pretty darn good busker/musician
  * Managed several meditation center kitchens 
  * Permaculture farming
  * Teaching ESL abroad


content:
  #- title: Projects # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: left
  #      title: Project name
  #      link: 
  #      link_text: 
  #      additional_links:
  #        - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #          icon: fab fa-github
  #          url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #        - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #          icon: fab fa-github
  #          url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #      quote: >
  #        Short overview of the project (optional)
  #      description: | # this will include new lines to allow paragraphs
  #        Description about the work on/with the project
  - title: Shopify Partner Support Specialist
    layout: list
    content:
      - layout: right
        title: Permanent Full-time
        sub_title: Third-Party Dev Support
        caption: Feb 2022 - present
        link: 
        quote: <h4>My current lead will say;</h4>
        description: | # this will include new lines to allow paragraphs
          * I routinely crush output metrics and QA scores and my Impact is high!
          * I learn specialized tools without much guidance because fun
          * We support third-party app, theme, and front-end devs (also Merchants/end-users)
          * We work with API deprecation cycles and product updates as they impact Partners
          * We work adjacent to/with teams like Incident Response, Governance, API Support, App Review/Audit, Enterprise & Strategic
          * I'm strong with tech issues and tricky human interactions
          * I show up and advocate with intensity, honesty, patience and persistance
  - title: Shopify Core Support
    layout: list
    content:
      - layout: right
        title: Permanent Full-time
        sub_title: Support Advisor
        caption: Dec 2021 - Jan 2022
        link: 
        quote: <h4>Moving up in this company;</h4>
        description: | # this will include new lines to allow paragraphs
          * Embracing diversity and change
          * Deep-dive issues and specialized tools
          * Improvising is my jam
          * Improving life for merchants and everyone else
          * Flexing my creativity and values
  - title: Shopify JSA Program
    layout: list
    content:
      - layout: right
        title: Nine Month Gauntlet
        sub_title: Junior Support Advisor
        caption: Feb - Nov 2021
        link: 
        quote: <h4>My former lead will say;</h4>
        description: | # this will include new lines to allow paragraphs
          * I'm self-aware and empathetic
          * I question process *a lot* and enjoy doing it
          * I show up for my team and connect 1-on-1 with courage and honesty
          * I reflect deeply on my work, growth, energy levels and opportunities
          * I keep my values up front and find meaning in my work
          * I manage my time and projects well
          * I make mistakes! (and own them)
  - title: Trades Experience
    layout: list
    content:
      - layout: right
        title: Boat Building
        sub_title: Self-employed/contract/freelance
        caption: 2009 - present
        link: 
        quote: 
        description: | # this will include new lines to allow paragraphs
          * 3 year apprenticeship under catamaran designer Richard Woods
          * 9 years contracting, custom fabrication and repair all over western Canada and beyond
          * Build and refit sailboats, yachts, work boats, research vessels
          * Hire crews as needed, deal with all aspects of business
  - title: Volunteering
    layout: list
    content:
      - layout: right
        title: Vipassana Meditation Centers - Canada & US
        sub_title: Kitchen Co-ordinator/Manager
        caption: 2005 - 2015 (intermittent)
        quote: 
        description: | # this will include new lines to allow paragraphs
          * Train and manage up to 20 new volunteers in 12 day rotations
          * Food and supply orders
          * Maintain FoodSafe protocols and practices
          * Routine maintenance and repairs
          * Cook amazing food for starving meditators!


      - layout: right
        title: AYNI Peru
        sub_title: ESL Teacher/Care Aide
        caption: 2002 - 2003
        quote:  
        description: | # this will include new lines to allow paragraphs
          * Daily lesson planning for grades 2 - 5
          * Work with staff and clients of inpatient care home
          * Distribute donations and organize international channels for same
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I spend my downtime surfing, picking wild edibles, playing chess, and MTB'ing the beautiful trails and hotsprings of the Kootenays with my dog. I'm passionate about reading, learning, healthy living, the environment, and social issues. I'm a lifelong *tangent learner* and I love growth-oriented challenges. I have a certificate in **Mental Health First-Aid** as well as **Crisis Intervention**, I've hitchhiked most of North-America, I've done stand-up comedy, *and I love writing elevator pitches!*

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
