# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Gamma Cray
title: Jake Of All Trades
email: onepathleft@protonmail.com
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: onepathleft.com/resume
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: "gammacray"
github_username:  "gammacray"
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Reddit
  icon: fab fa-reddit-alien
  url: reddit.com/u/onepathleft
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs

  Hello! In 2021 I'm making the jump from 20 years in trades to an online skillset and a healthier lifestyle. I'm incredibly fond of working with people from around the world, from all walks of life. I thrive on discovering the goals of others and finding ways to get them there. It's a lot like building sailboats - pulling lines out of thin air and making them real with any tool available, many of them improvised or built specifically for the task. On a similar level I'd like to humblebrag that this CV was composed with a template which uses a combination of Markdown, YAML, and Liquid languages before being converted to PDF - just because it's possible!

  I bring wisdom and experience from multiple fields including;
  * Freelance writing and website design
  * Sailboat building and repair
  * Tiny-home construction
  * Semi-professional musician
  * Managing several meditation centers 
  * Permaculture farming
  * Teaching ESL abroad


content:
  #- title: Projects # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: left
  #      title: Project name
  #      link: 
  #      link_text: 
  #      additional_links:
  #        - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #          icon: fab fa-github
  #          url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #        - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #          icon: fab fa-github
  #          url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #      quote: >
  #        Short overview of the project (optional)
  #      description: | # this will include new lines to allow paragraphs
  #        Description about the work on/with the project
  - title: Shopify Core Support
    layout: list
    content:
      - layout: right
        title: Permanent Full-time
        sub_title: Support Advisor
        caption: December 2021 - present
        link: 
        quote: <h4>Where I see myself going in the company;</h4>
        description: | # this will include new lines to allow paragraphs
          * A team that works with tricky issues and specialized tools
          * A role that thrives on improvising and blazing trail
          * A team that embraces diversity
  - title: Shopify JSA Program
    layout: list
    content:
      - layout: right
        title: Nine Months of Gauntlet
        sub_title: Junior Support Advisor
        caption: February - November 2021
        link: 
        quote: <h4>I believe my (JSA) lead will say;</h4>
        description: | # this will include new lines to allow paragraphs
          * I'm self-aware and empathetic
          * I question process *a lot* and enjoy doing it
          * I show up for my team and connect 1-on-1 with courage and honesty
          * I reflect deeply on my work, growth, energy levels and opportunities
          * I manage my time and projects well
          * I keep my values up front and find meaning in my work
          * I make mistakes! (and own them)
  - title: Trades Experience
    layout: list
    content:
      - layout: right
        title: Boat Building
        sub_title: Self-employed/contract/freelance
        caption: 2009 - present
        link: 
        quote: 
        description: | # this will include new lines to allow paragraphs
          * 3 year apprenticeship under catamaran designer Richard Woods
          * 9 years contracting, custom fabrication and repair all over western Canada
          * Build and refit sailboats, yachts, work boats, research vessels
          * Hire crews as needed, deal with all aspects of business
  - title: Volunteering
    layout: list
    content:
      - layout: right
        title: Vipassana Meditation Centers - Canada & US
        sub_title: Kitchen Co-ordinator/Manager
        caption: 2005 - 2015 (intermittent)
        quote: 
        description: | # this will include new lines to allow paragraphs
          * Train and manage up to 20 new volunteers in 12 day rotations
          * Food and supply orders
          * Maintain FoodSafe protocols and practices
          * Routine maintenance and repairs


      - layout: right
        title: AYNI Peru
        sub_title: ESL Teacher/Care Aide
        caption: 2002 - 2003
        quote:  
        description: | # this will include new lines to allow paragraphs
          * Daily lesson planning for grades 2 - 5
          * Work with staff and clients of inpatient care home
          * Distribute donations and organize international channels for same
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I spend my downtime surfing, picking wild mushrooms, playing chess, and walking the beautiful forests and trails of the Kootenays with my dog. I'm passionate about reading, learning, healthy living, the environment, and social issues. I believe a better world is possible and I'm extremely happy to be here to see it unfold. I have a certificate in **Mental Health First-Aid**, I've hitchhiked most of North-America, I've done stand-up comedy, and I love writing elevator pitches!

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
